import { createUseStyles } from "react-jss";

export const slidesInfo = [
    {
        cTitle: 'Baba',
        cDescription: "Galib has a family with 3 children and a wife. Galib always think about his falimy member's demands. But does anyone think about Galib's demands?",
        cLandscape: '/Golpo Images/baba/baba-landscape.webp',
        cBanner: '/Golpo Images/baba/baba-banner.webp',
        cPortrait: '/Golpo Images/baba/baba-portrait.webp',
        cLogo: '/Golpo Images/baba/baba-logo.webp',
        cCard: '/Golpo Images/baba/baba-cardratio.webp',
        cSquare: '/Golpo Images/baba/baba-square.webp',
        cLink: '/audiostory/jibonersarangsho',
        cTrailerLink: '/audiostory/jibonersarangsho/trailer',
        cYtId: 'bktw_fQWXfM',
        cTrailerYtId: 'oOr_q61Dilg',
        cGenre: ['Drama', 'Family', 'Romantic'],
        cinteract: 'Read',
        width: 200,
        height: 200,
    },
    {
        cTitle: 'Jiboner Sharangsho',
        cDescription: 'Two different love story of a girl Inni, two boy Jaayaan and Omi And two different fate.',
        cLandscape: '/Golpo Images/JibonerSarangsho/jiboner-sarangsho-landscape.webp',
        cBanner: '/Golpo Images/JibonerSarangsho/jiboner-sarangsho-banner.webp',
        cPortrait: '/Golpo Images/JibonerSarangsho/jiboner-sarangsho-portrait.webp',
        cLogo: '/Golpo Images/JibonerSarangsho/jiboner-sarangsho-logo.webp',
        cCard: '/Golpo Images/JibonerSarangsho/jibonersarangsho-cardratio.webp',
        cSquare: '/Golpo Images/JibonerSarangsho/jiboner-sarangsho-squares.webp',
        cLink: '/audiostory/jibonersarangsho',
        cTrailerLink: '/audiostory/jibonersarangsho/trailer',
        cYtId: 'bktw_fQWXfM',
        cTrailerYtId: 'oOr_q61Dilg',
        cGenre: ['Romantic'],
        cinteract: 'Listen',
        width: 200,
        height: 200,
    },
    {
        cTitle: 'Chauler Bosta',
        cDescription: 'A chairman gave a street beggar half KG sack of rice. But later so many things happen for that sack of rice.',
        cLandscape: '/Golpo Images/ChaulerBosta/chauler-bosta-landscape.webp',
        cBanner: '/Golpo Images/ChaulerBosta/chauler-bosta-banner.webp',
        cPortrait: '/Golpo Images/ChaulerBosta/chauler-bosta-portrait.webp',
        cLogo: '/Golpo Images/ChaulerBosta/logo.webp',
        cCard: '/Golpo Images/ChaulerBosta/chaulerbosta-cardratio.webp',
        cSquare: '/Golpo Images/ChaulerBosta/chauler-bosta-squares.webp',
        cLink: '/animationmovie/chaulerbosta',
        cTrailerLink: '/animationmovie/chaulerbosta/trailer',
        cYtId: 'bktw_fQWXfM',
        cTrailerYtId: 'oOr_q61Dilg',
        cGenre: ['Politics', 'Drama', 'Thriller'],
        cinteract: 'Watch',
        width: 200,
        height: 200,
    },
    {
        cTitle: 'Chesrami',
        cDescription: "Arina is very excited with his father's story on last year of his school life.",
        cLandscape: '/Golpo Images/Chesrami/chearami-landscape.webp',
        cBanner: '/Golpo Images/Chesrami/chesrami-banner.webp',
        cPortrait: '/Golpo Images/Chesrami/chesrami-portrait.webp',
        cLogo: '/Golpo Images/Chesrami/chesrami logo.webp',
        cCard: '/Golpo Images/Chesrami/chesrami-cardratio.webp',
        cSquare: '/Golpo Images/Chesrami/chesrami-squares.webp',
        cLink: '/audiostory/chesrami',
        cTrailerLink: '/audiostory/chesrami/trailer',
        cYtId: 'R9clu4OzhSg',
        cTrailerYtId: 'VgGRuUVkC60',
        cGenre: ['Romantic', 'Thriller', 'Drama'],
        cinteract: 'Listen',
        width: 200,
        height: 200,
    },
    {
        cTitle: 'Porichoy',
        cDescription: "Abir is identityless from his birth. Nurse Hosne Ara save him from some greedy doctors. His whole life goes on in search of his real identity.",
        cLandscape: '/Golpo Images/Porichoy/porichoy-landscape.webp',
        cBanner: '/Golpo Images/Porichoy/porichoy-banner.webp',
        cPortrait: '/Golpo Images/Porichoy/porichoy-portrait.webp',
        cLogo: '/Golpo Images/Porichoy/porichoy-logo.webp',
        cCard: '/Golpo Images/Porichoy/porichoy-cardratio.webp',
        cSquare: '/Golpo Images/Porichoy/porichoy-squares.webp',
        cLink: '/audiostory/porichoy',
        cTrailerLink: '/audiostory/porichoy/trailer',
        cYtId: 'R9clu4OzhSg',
        cTrailerYtId: 'VgGRuUVkC60',
        cGenre: ['Thriller', 'Drama', 'Romantic'],
        cinteract: 'Read',
        width: 200,
        height: 200,
    },
    {
        cTitle: 'Irsha',
        cDescription: "Story of a First boy, Anik; Second boy, Protik; Protik's best friend, Arif; and his father, Ronok who hate his son.",
        cLandscape: '/Golpo Images/Irsha/irsha-landscape.webp',
        cBanner: '/Golpo Images/Irsha/irsha-banner.webp',
        cPortrait: '/Golpo Images/Irsha/irsha-portrait.webp',
        cLogo: '/Golpo Images/Irsha/irsha-logo.webp',
        cCard: '/Golpo Images/Irsha/irsha-cardratio.webp',
        cSquare: '/Golpo Images/Irsha/irsha-squares.webp',
        cLink: '/audiostory/irsha',
        cTrailerLink: '/audiostory/irsha/trailer',
        cYtId: 'R9clu4OzhSg',
        cTrailerYtId: 'VgGRuUVkC60',
        cGenre: ['Horror', 'Thriller'],
        cinteract: 'Listen',
        width: 200,
        height: 200,
    },
    {
        cTitle: 'Love Dot Com',
        cDescription: "Sohan is not that much interested in romanticism. But a girl awakens love in him. Now what will Sohan do?",
        cLandscape: '/Golpo Images/loveDotCom/lovedotcom-landscape.webp',
        cBanner: '/Golpo Images/loveDotCom/lovedotcom-banner.webp',
        cPortrait: '/Golpo Images/loveDotCom/lovedotcom-portrait.webp',
        cLogo: '/Golpo Images/loveDotCom/lovedotcom-logo.webp',
        cCard: '/Golpo Images/loveDotCom/lovedotcom-cardratio.webp',
        cSquare: '/Golpo Images/loveDotCom/lovedotcom-squres.webp',
        cLink: '/shortstoryseries/lovedotcom',
        cTrailerLink: '/shortstoryseries/lovedotcom/trailer',
        cYtId: 'R9clu4OzhSg',
        cTrailerYtId: 'VgGRuUVkC60',
        cGenre: ['Romantic', 'Drama'],
        cinteract: 'Read',
        width: 200,
        height: 200,
    },
    {
        cTitle: 'Opurno Valobasha',
        cDescription: "Love is amazing and the story is about it's iteration among Raj, Rafin, Ridoy and Rita.",
        cLandscape: '/Golpo Images/opurnovalobasha/opurnovalobasha-landscape.webp',
        cBanner: '/Golpo Images/opurnovalobasha/opurnovalobasha-banner.webp',
        cPortrait: '/Golpo Images/opurnovalobasha/opurnovalobasha-portrait.webp',
        cLogo: '/Golpo Images/opurnovalobasha/opurnovalobasha-logo.webp',
        cCard: '/Golpo Images/opurnovalobasha/opurnovalobasha-cardratio.webp',
        cSquare: '/Golpo Images/opurnovalobasha/opurnovalobasha-square.webp',
        cLink: '/audiostory/jibonersarangsho',
        cTrailerLink: '/audiostory/jibonersarangsho/trailer',
        cYtId: 'bktw_fQWXfM',
        cTrailerYtId: 'oOr_q61Dilg',
        cGenre: ['Romantic', 'Drama'],
        cinteract: 'Listen',
        width: 200,
        height: 200,
    },
]


export const useStyles = createUseStyles({
    sliderContainer: {
        "& .slick-list": {
            marginLeft: "40px !important",
            marginRight: "40px !important",
        },

        // Media query
        "@media screen and (max-width: 850px)": {
            "& .slick-list": {
                marginLeft: "0px !important",   // Correcting margins for smaller screens
                marginRight: "20px !important",
            },
            "& .slick-prev": {
                display: "none !important",
            },

            "& .slick-next ": {
                display: "none !important",
            },
        }

    }
});
